# Generated by Django 2.1.5 on 2019-02-11 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20190202_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrecords',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.WebPage'),
        ),
        migrations.AlterModelTable(
            name='accessrecords',
            table='accessrecords',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topic',
        ),
        migrations.AlterModelTable(
            name='webpage',
            table='webpage',
        ),
    ]
