sudo: required
language: generic
services:
    - docker

before_install:
    - docker-compose up --build -d
    - docker ps


script:
    - docker-compose -f docker-compose.yml up -d
    - docker exec -it python manage.py test polls
