sudo: required
language: generic
services:
    - docker

before_install:
    - docker-compose up --build
    - docker ps


script:
    - echo 'Tests moved to docker compose' # docker-compose run django python manage.py test polls

