sudo: required
language: generic
services:
    - docker

before_install:
    - docker-compose up --build -d


script:
    - docker inspect -f \
    '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}:3306' \
    docker_django-mysql #inspeting is mysql is ok
    -  docker-compose exec django  pytest


