sudo: required
services:
    - docker

before_install:
    - docker-compose up   -d
    - docker ps
    - docker-compose run --no-deps django python manage.py test polls

script:
    - docker-compose run django python manage.py test polls

