sudo: required
language: generic
services:
    - docker

before_install:
    - docker-compose up --build -d
    - docker ps


script:
    - docker-compose -f docker-compose.yml run django python manage.py test polls

