sudo: required
language: generic
services:
    - docker

before_install:
    - docker-compose up --build -d
    - docker ps


script:
    - docker inspect -f \
    '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}:3306' \
    docker_django-mysql
    -  docker-compose exec django  pytest


