sudo: required
language: generic
services:
    - docker

before_install:
    - docker-compose up -d

script:
    - echo "docker-compose run django python manage.py test polls"
deploy:
   provider: elasticbeanstalk
   region: "us-east-2"
   app: "docker-django"
   env: "DockerDjango-env"
   bucket_name: "elasticbeanstalk-us-east-2-868028514381"
   bucket_path: "docker-django"
   on:
     branch: master
   access_key_id: "$AWS_ACCESS_KEY"
   secret_key_id:
     secure: "$AWS_SECRET_KEY"




