###############################################################################
#  In settings.py:
#       DATABASES = {
#            'default': {
#                'ENGINE': 'django.db.backends.mysql',
#                'HOST': 'mysql',
#                ...
#            }
#        }
#
#  In PyCharm configurations:
#       Host: 0.0.0.0 - Port: 8000
#       Python interpreter: Select the docker ...
###############################################################################
version: "3.1"

volumes:
    db-data:

services:

    django:
      build: .
      container_name: ${PROJECT_NAME}-django
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/first_project
      ports:
        - "8000:8000"
      depends_on:
        - mysql

    mysql:
      image: mysql:5.6
      container_name: ${PROJECT_NAME}-mysql
      volumes:
        - db-data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=docker_root
        - MYSQL_DATABASE=docker_django_db
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=dbpw
      ports:
        - "8306:3306"


    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
          - PMA_ARBITRARY=1
        restart: always
        ports:
             - 8082:80
        volumes:
             - /session

