###############################################################################
#  In settings.py:
#       DATABASES = {
#            'default': {
#                'ENGINE': 'django.db.backends.mysql',
#                'HOST': 'mysql',
#                ...
#            }
#        }
#
#  In PyCharm configurations:
#       Host: 0.0.0.0 - Port: 8000
#       Python interpreter: Select the docker ...
###############################################################################
version: "3.1"



services:

    django:
      image: mikegreat/docker-django
      container_name: ${PROJECT_NAME}-django
      command: .entrypoint.sh
      env_file:
        - .env
      volumes:
        - ./app:/app
        - static_volume:/app/static
      expose:
         - 8000
      depends_on:
        - mysql

    mysql:
      image: mysql:5.6
      container_name: ${PROJECT_NAME}-mysql
      volumes:
        - mysql-data:/var/lib/mysql
      ports:
        - "8306:3306"


    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: ${PROJECT_NAME}-phpmyadmin
      environment:
          - PMA_ARBITRARY=1
      restart: always
      ports:
             - 8082:80
      volumes:
             - /session

    nginx:
      image: mikegreat/docker-nginx
      container_name: ${PROJECT_NAME}-nginx
      volumes:
           - static_volume:/app/static
      ports:
           - 1337:80
      depends_on:
          - django


volumes:
  mysql-data:
  static_volume:

