version: 2
jobs:
  build:
    working_directory: ~/first_project
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start container and verify it's working
          command: |
             docker-compose up --build  -d
             docker-compose start  mysql
      - run:
          name: Let client talk to server
          command:  docker exec docker_django-django python manage.py test polls
