version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start container and verify it's working
          command: docker-compose up --build -d
      - run:
          name: Let client talk to server
          command: docker-compose run django  --no-deps python manage.py test polls
