# Generated by Django 2.1.5 on 2019-02-11 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190211_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrecords',
            old_name='name',
            new_name='webpage',
        ),
    ]
