# Generated by Django 2.1.5 on 2019-03-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190211_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'new_users',
            },
        ),
    ]
